export const WORKER_COMMANDS = {
  INGEST_ZIP: 'INGEST_ZIP',
  CANCEL_JOB: 'CANCEL_JOB'
};

export const WORKER_EVENTS = {
  STARTED: 'STARTED',
  PROGRESS: 'PROGRESS',
  ENTRY_ERROR: 'ENTRY_ERROR',
  COMPLETE: 'COMPLETE',
  ERROR: 'ERROR',
  CANCELLED: 'CANCELLED'
};
